/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Achievements: typeof import('./src/components/Achievements.vue')['default']
    DeleteTransaction: typeof import('./src/components/Modals/DeleteTransaction.vue')['default']
    Goals: typeof import('./src/components/Goals.vue')['default']
    InfoCard: typeof import('./src/components/InfoCard.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    ReleaseNotes: typeof import('./src/components/Modals/ReleaseNotes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavingsAccount: typeof import('./src/components/Modals/SavingsAccount.vue')['default']
    Settings: typeof import('./src/components/Modals/Settings.vue')['default']
    Statistics: typeof import('./src/components/Statistics.vue')['default']
    TableDisplay: typeof import('./src/components/TableDisplay.vue')['default']
    TimeFrame: typeof import('./src/components/Modals/TimeFrame.vue')['default']
    Transaction: typeof import('./src/components/Modals/Transaction.vue')['default']
  }
}
